/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedMovimientosRouteImport } from './routes/_authenticated/movimientos'
import { Route as AuthenticatedMiInversionRouteImport } from './routes/_authenticated/mi-inversion'
import { Route as AuthenticatedInversoresRouteImport } from './routes/_authenticated/inversores'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCortesRouteImport } from './routes/_authenticated/cortes'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMovimientosRoute =
  AuthenticatedMovimientosRouteImport.update({
    id: '/movimientos',
    path: '/movimientos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMiInversionRoute =
  AuthenticatedMiInversionRouteImport.update({
    id: '/mi-inversion',
    path: '/mi-inversion',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInversoresRoute = AuthenticatedInversoresRouteImport.update({
  id: '/inversores',
  path: '/inversores',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCortesRoute = AuthenticatedCortesRouteImport.update({
  id: '/cortes',
  path: '/cortes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/cortes': typeof AuthenticatedCortesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/inversores': typeof AuthenticatedInversoresRoute
  '/mi-inversion': typeof AuthenticatedMiInversionRoute
  '/movimientos': typeof AuthenticatedMovimientosRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/cortes': typeof AuthenticatedCortesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/inversores': typeof AuthenticatedInversoresRoute
  '/mi-inversion': typeof AuthenticatedMiInversionRoute
  '/movimientos': typeof AuthenticatedMovimientosRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/cortes': typeof AuthenticatedCortesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/inversores': typeof AuthenticatedInversoresRoute
  '/_authenticated/mi-inversion': typeof AuthenticatedMiInversionRoute
  '/_authenticated/movimientos': typeof AuthenticatedMovimientosRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/cortes'
    | '/dashboard'
    | '/inversores'
    | '/mi-inversion'
    | '/movimientos'
    | '/usuarios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/cortes'
    | '/dashboard'
    | '/inversores'
    | '/mi-inversion'
    | '/movimientos'
    | '/usuarios'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/cortes'
    | '/_authenticated/dashboard'
    | '/_authenticated/inversores'
    | '/_authenticated/mi-inversion'
    | '/_authenticated/movimientos'
    | '/_authenticated/usuarios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/movimientos': {
      id: '/_authenticated/movimientos'
      path: '/movimientos'
      fullPath: '/movimientos'
      preLoaderRoute: typeof AuthenticatedMovimientosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mi-inversion': {
      id: '/_authenticated/mi-inversion'
      path: '/mi-inversion'
      fullPath: '/mi-inversion'
      preLoaderRoute: typeof AuthenticatedMiInversionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inversores': {
      id: '/_authenticated/inversores'
      path: '/inversores'
      fullPath: '/inversores'
      preLoaderRoute: typeof AuthenticatedInversoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cortes': {
      id: '/_authenticated/cortes'
      path: '/cortes'
      fullPath: '/cortes'
      preLoaderRoute: typeof AuthenticatedCortesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCortesRoute: typeof AuthenticatedCortesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInversoresRoute: typeof AuthenticatedInversoresRoute
  AuthenticatedMiInversionRoute: typeof AuthenticatedMiInversionRoute
  AuthenticatedMovimientosRoute: typeof AuthenticatedMovimientosRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCortesRoute: AuthenticatedCortesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInversoresRoute: AuthenticatedInversoresRoute,
  AuthenticatedMiInversionRoute: AuthenticatedMiInversionRoute,
  AuthenticatedMovimientosRoute: AuthenticatedMovimientosRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
