/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedConfiguracionRouteImport } from './routes/_authenticated/configuracion'
import { Route as AuthenticatedCortesRouteImport } from './routes/_authenticated/cortes'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedHistorialRouteImport } from './routes/_authenticated/historial'
import { Route as AuthenticatedInversoresRouteImport } from './routes/_authenticated/inversores'
import { Route as AuthenticatedLiquidacionesRouteImport } from './routes/_authenticated/liquidaciones'
import { Route as AuthenticatedMiInversionRouteImport } from './routes/_authenticated/mi-inversion'
import { Route as AuthenticatedMovimientosRouteImport } from './routes/_authenticated/movimientos'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedConfiguracionRoute =
  AuthenticatedConfiguracionRouteImport.update({
    id: '/configuracion',
    path: '/configuracion',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCortesRoute = AuthenticatedCortesRouteImport.update({
  id: '/cortes',
  path: '/cortes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistorialRoute = AuthenticatedHistorialRouteImport.update({
  id: '/historial',
  path: '/historial',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInversoresRoute = AuthenticatedInversoresRouteImport.update({
  id: '/inversores',
  path: '/inversores',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLiquidacionesRoute =
  AuthenticatedLiquidacionesRouteImport.update({
    id: '/liquidaciones',
    path: '/liquidaciones',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMiInversionRoute =
  AuthenticatedMiInversionRouteImport.update({
    id: '/mi-inversion',
    path: '/mi-inversion',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMovimientosRoute =
  AuthenticatedMovimientosRouteImport.update({
    id: '/movimientos',
    path: '/movimientos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/configuracion': typeof AuthenticatedConfiguracionRoute
  '/cortes': typeof AuthenticatedCortesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/historial': typeof AuthenticatedHistorialRoute
  '/inversores': typeof AuthenticatedInversoresRoute
  '/liquidaciones': typeof AuthenticatedLiquidacionesRoute
  '/mi-inversion': typeof AuthenticatedMiInversionRoute
  '/movimientos': typeof AuthenticatedMovimientosRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/configuracion': typeof AuthenticatedConfiguracionRoute
  '/cortes': typeof AuthenticatedCortesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/historial': typeof AuthenticatedHistorialRoute
  '/inversores': typeof AuthenticatedInversoresRoute
  '/liquidaciones': typeof AuthenticatedLiquidacionesRoute
  '/mi-inversion': typeof AuthenticatedMiInversionRoute
  '/movimientos': typeof AuthenticatedMovimientosRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/configuracion': typeof AuthenticatedConfiguracionRoute
  '/_authenticated/cortes': typeof AuthenticatedCortesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/historial': typeof AuthenticatedHistorialRoute
  '/_authenticated/inversores': typeof AuthenticatedInversoresRoute
  '/_authenticated/liquidaciones': typeof AuthenticatedLiquidacionesRoute
  '/_authenticated/mi-inversion': typeof AuthenticatedMiInversionRoute
  '/_authenticated/movimientos': typeof AuthenticatedMovimientosRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mcp'
    | '/reset-password'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/configuracion'
    | '/cortes'
    | '/dashboard'
    | '/historial'
    | '/inversores'
    | '/liquidaciones'
    | '/mi-inversion'
    | '/movimientos'
    | '/usuarios'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mcp'
    | '/reset-password'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/configuracion'
    | '/cortes'
    | '/dashboard'
    | '/historial'
    | '/inversores'
    | '/liquidaciones'
    | '/mi-inversion'
    | '/movimientos'
    | '/usuarios'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/mcp'
    | '/reset-password'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/configuracion'
    | '/_authenticated/cortes'
    | '/_authenticated/dashboard'
    | '/_authenticated/historial'
    | '/_authenticated/inversores'
    | '/_authenticated/liquidaciones'
    | '/_authenticated/mi-inversion'
    | '/_authenticated/movimientos'
    | '/_authenticated/usuarios'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/configuracion': {
      id: '/_authenticated/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof AuthenticatedConfiguracionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cortes': {
      id: '/_authenticated/cortes'
      path: '/cortes'
      fullPath: '/cortes'
      preLoaderRoute: typeof AuthenticatedCortesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historial': {
      id: '/_authenticated/historial'
      path: '/historial'
      fullPath: '/historial'
      preLoaderRoute: typeof AuthenticatedHistorialRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inversores': {
      id: '/_authenticated/inversores'
      path: '/inversores'
      fullPath: '/inversores'
      preLoaderRoute: typeof AuthenticatedInversoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/liquidaciones': {
      id: '/_authenticated/liquidaciones'
      path: '/liquidaciones'
      fullPath: '/liquidaciones'
      preLoaderRoute: typeof AuthenticatedLiquidacionesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mi-inversion': {
      id: '/_authenticated/mi-inversion'
      path: '/mi-inversion'
      fullPath: '/mi-inversion'
      preLoaderRoute: typeof AuthenticatedMiInversionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/movimientos': {
      id: '/_authenticated/movimientos'
      path: '/movimientos'
      fullPath: '/movimientos'
      preLoaderRoute: typeof AuthenticatedMovimientosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedConfiguracionRoute: typeof AuthenticatedConfiguracionRoute
  AuthenticatedCortesRoute: typeof AuthenticatedCortesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHistorialRoute: typeof AuthenticatedHistorialRoute
  AuthenticatedInversoresRoute: typeof AuthenticatedInversoresRoute
  AuthenticatedLiquidacionesRoute: typeof AuthenticatedLiquidacionesRoute
  AuthenticatedMiInversionRoute: typeof AuthenticatedMiInversionRoute
  AuthenticatedMovimientosRoute: typeof AuthenticatedMovimientosRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedConfiguracionRoute: AuthenticatedConfiguracionRoute,
  AuthenticatedCortesRoute: AuthenticatedCortesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHistorialRoute: AuthenticatedHistorialRoute,
  AuthenticatedInversoresRoute: AuthenticatedInversoresRoute,
  AuthenticatedLiquidacionesRoute: AuthenticatedLiquidacionesRoute,
  AuthenticatedMiInversionRoute: AuthenticatedMiInversionRoute,
  AuthenticatedMovimientosRoute: AuthenticatedMovimientosRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
